### ISSUE TITLE
Fix ModShot not building for Windows using GitHub Actions

### ISSUE THREAD

**Issue by rkevin-arch** [Astrabit-ST/ModShot-Core#42]
More CI failures

![image](https://media.tenor.co/images/f0f4b28705fbe5cf7e418156280c9117/raw)

https://github.com/rkevin-arch/Modshot-Core/runs/3151243910?check_suite_focus=true

**Comment by melody-rs** [comment]
~~That gif fits perfectly~~
Yeah that's not good at all

**Comment by rkevin-arch** [comment]
Update on this issue: after bumping to SDL2 2.0.14, Windows now [builds successfully](https://github.com/rkevin-arch/Modshot-Core/actions/runs/1063524382). Linux is having issues with iconv (likely a newly added dependency), which might be as simple as just installing it in the CI environment. Should be fixed soon*

*: but not now because I'm busy with other stuff :(
