### ISSUE TITLE
Immediately crashing after pressing media keys

### ISSUE THREAD

**Issue by thehatkid** [Astrabit-ST/Modshot-Core#46]
ModShot build for Windows (https://github.com/Astrabit-ST/ModShot-Core/commit/f436a62b8dfbd76feb200963b4e226ad55a1bd96)

After pressing an "media" key on keyboard *(like Mute Volume, Next/Prev track, open brower, etc.)* the ModShot will immediately 
 crash without reason and confirmations.

**Comment by thehatkid** [comment]
Probably fixed in new commits.

**Comment by melody-rs** [comment]
Still not fixed.
