### ISSUE TITLE
Constant Encoding

### ISSUE THREAD

**Issue by zimberzimber** [Astrabit-ST/Modshot-Core#47]
Constants defined within C++ (i.e `Oneshot::SAVE_PATH`) are ASCII-8BIT encoded, causing encoding compatibility issues in Ruby scripts when trying to merge them with UTF-8 strings (Ruby's default) containing non-ASCII characters.
Major problem for players with non-ASCII characters in their name.

The error is the same as running this code:
```ruby
ascii = String.new("ł", encoding:"ASCII-8BIT")
utf8 = "ł"

puts ascii.encoding, ascii 
puts utf8.encoding, utf8
puts ascii + utf8
```

Replicated by creating a new Windows account with non-ASCII characters in its name, and debugging OSFM.

It can be worked around on the Ruby layer by initializing and using  a separate constant, which is just a re-encoding of the original constant. (via `.force_encoding("UTF-8")`)

**Comment by melody-rs** [comment]
This should be fixed now.
