### ISSUE TITLE
meson.build:16:11: ERROR: lexer

### ISSUE THREAD

**Issue by creativegamer03** [Astrabit-ST/ModShot-Core#87]
build process went fine until I proceed to the meson build step:
`meson build --prefix="$PWD/build.out" --bindir=.`

Here is the error log of it: (meson-log.txt)
```
Build started at 2022-11-22T22:48:22.035901
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.45.1
Source dir: /home/cg03-dev/Downloads/ModShot-Core-master
Build dir: /home/cg03-dev/Downloads/ModShot-Core-master/build
Build type: native build

meson.build:16:11: ERROR: lexer
compilers = {
           ^
```

**Comment by thehatkid** [comment]
Please, update your Meson build system, you are using `0.45.1`, but `meson.build` requires Meson 0.60.0 and higher.

**Comment by creativegamer03** [comment]
i did but apt install says its the latest

**Comment by thehatkid** [comment]
You can download [Meson](https://github.com/mesonbuild/meson/releases/tag/0.64.0) and then use `meson.py build --prefix="$PWD/build.out" --bindir=.`, or you also can use Python with PIP and install `meson` package (`pip3 install --upgrade meson`).

**Comment by eli-schwartz** [comment]
How was this error encountered by the way? `meson_version: '>=0.60.0'` (updated from 0.56.0 in June) means that Meson should always error out and tell you that you need a newer version of Meson.

**Comment by melody-rs** [comment]
Maybe their meson version couldn't parse the meson build files?

**Comment by eli-schwartz** [comment]
Did some tests and answered my own question... if Meson cannot syntactically parse the file it cannot evaluate the first line and detect the minimum required meson version. For example this fails with Meson 0.64.1:
```meson
project(
    'test',
    meson_version: '>=2.3.0',
)

foo ======= bar
```

```
t/meson.build:6:6: ERROR: Expecting eof got equal.
foo ======= bar
      ^
```

That's Meson's fault then. Maybe we can do something about this.
